### ISSUE TITLE
ADB over USB not working

### ISSUE THREAD

**Issue by cmorlok** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#101]
It's not possible to connect to ADB over USB (while it's possible via network).

It might be a kernel error; the driver doesn't accept the adb function:

```
# echo 0 > /sys/class/android_usb/android0/enable
# echo diag,serial_smd,serial_tty,mass_storage,adb > /sys/class/android_usb/android0/functions
# cat /sys/class/android_usb/android0/functions
diag,serial_smd,serial_tty,mass_storage
# echo diag,serial_smd,serial_tty,adb > /sys/class/android_usb/android0/functions
# cat /sys/class/android_usb/android0/functions
diag,serial_smd,serial_tty
```

**Comment by sergiopoverony** [comment]
Work is fine. Need switch OFF underWIN check the authenticity of the installed drivers

**Comment by cmorlok** [comment]
@sergiopoverony Can you please post the output of

```
cat /sys/class/android_usb/android0/functions
```

**Comment by sergiopoverony** [comment]
@cmorlok I copy adb.exe, AdbWinApi.dll and AdbWinUsbApi.dll from unpacket official FW by 4.0.0_20160517-1201-piccolo-user-851-FW
I Copy this files to my Windows folder
WinXP and device pictures
Use connection - MTP and ADB  CM13 
![qip shot - screen 1025](https://cloud.githubusercontent.com/assets/5286127/16410444/f4a12ea8-3d3b-11e6-9ae5-c90a6409a1dd.png)
Use connection - Charger and ADB 
![screenshot_20160628-140627](https://cloud.githubusercontent.com/assets/5286127/16410211/dc50dcd2-3d3a-11e6-8e63-a5e8a5f03cdb.png)
![qip shot - screen 1024](https://cloud.githubusercontent.com/assets/5286127/16410202/d1f7effa-3d3a-11e6-9f74-534211dbc713.png)

**Comment by cmorlok** [comment]
Sorry my fault. ADB has been downgraded with the latest system update. Everything is fine with the correct version.
