### ISSUE TITLE
Some apps report "Your device isn't compatible with this version" in the Play Store

### ISSUE THREAD

**Issue by tonke90** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#106]
Some (a lot) of apps report "Your device isn't compatible with this version" in the Play Store, when either installing or updating them. Two examples are Google Inbox and Signal Messanger. Tested with gapps nano.

This only happens with builds starting from _cm-13.0-20160612-UNOFFICIAL-piccolo_. It could maybe be relate to the change regarding the fingerprint.

**Comment by cmorlok** [comment]
Will be fixed in the next version. Root cause was the incorrect OpenGL definition, see #107 and https://github.com/bq-dev/android_device_bq_piccolo/commit/919dc7fe4776f50e9bc7f10c4e1403404c12f442

**Comment by cmorlok** [comment]
Fixed in build 20160709.
