### ISSUE TITLE
Not supported OpenGL ES2 - CM13

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#107]
After update from 03.07.2016 i see error messages on TeamViewer app about "Device not supported. This device does Not support OpenGL ES 2.0, which is a minimum requirement for this app." in oldy version 20.06.2016 all work fine. 

![screenshot_20160707-072931](https://cloud.githubusercontent.com/assets/5286127/16641143/2b8fceb0-4417-11e6-8ac5-b90186b68d87.png)

**Comment by cmorlok** [comment]
Will be fixed in the next build, see https://github.com/bq-dev/android_device_bq_piccolo/commit/919dc7fe4776f50e9bc7f10c4e1403404c12f442

**Comment by sergiopoverony** [comment]
oh. lost sign. i edit my build.prop - all work fine. ready wait update ;)

**Comment by cmorlok** [comment]
Fixed in build 20160709.
