### ISSUE TITLE
Pause and volume buttons from headphones doesn't work

### ISSUE THREAD

**Issue by Greatdroid** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#108]
In this last build can't use volume and play/pause buttons from the headphones. It does not work.

**Comment by cmorlok** [comment]
@Kra1o5 Is there any reason why you renamed the keylayout in https://github.com/bq-dev/android_device_bq_piccolo/commit/e158c606bbe047dd56c8588cfb1a2a1e3e192896? Shouldn't it be Headset.kl? We had to rename it a long time ago to get the buttons working, see https://github.com/piccolo-dev/android_device_bq_piccolo/commit/b3f91535716469e9707938e11da4831122f7beae.

**Comment by Kra1o5** [comment]
Hi @cmorlok ,

It fixed issue for picmt so I merged it to piccolo, if this broken it on piccolo I will revert it without problems for next release.

Greetings

**Comment by cmorlok** [comment]
I will test which kl file is needed and fix it before the next weekly build.

**Comment by Kra1o5** [comment]
As I can see, reverting this commit is fine.

**Comment by Kra1o5** [comment]
Reverted here: https://github.com/bq-dev/android_device_bq_piccolo/commit/eb3b7fc2cc2ba5687ae5cde609b4ed65eb604897
