### ISSUE TITLE
CM13 - OTA update MD5 error

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#112]
Ota update cm-13.0-20160725-UNOFFICIAL after download show ERROR message - unable check md5

**Comment by sergiopoverony** [comment]
fast reaction - after 10 min issuses - update is closed and not download )))

**Comment by Kra1o5** [comment]
Yes, corrupt upload, Im reuploading now.

**Comment by sergiopoverony** [comment]
@Kra1o5 Thanks. Good.

**Comment by Kra1o5** [comment]
Fixed now.
