### ISSUE TITLE
host_driver_logs_current.txt

### ISSUE THREAD

**Issue by 1tft** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#113]
Hello,
at internal storage (storage/emulated/0/wlan_logs) I find a file called host_driver_logs_current.txt which is rapidly growing everytime I use WLAN. I can't see any logrotation etc..
Could this be an issue with a forgotten debugging option? 

My setup
Version: RC [2016/07/31]
Firmwarebase: 4.1.0 (Android 6.0.1) 
Installation/Upgrade: no upgrade, full clean installation with a factory reset prior installation

**Comment by Kra1o5** [comment]
Hi @1tft ,

Fixed, will be present in next release :) .

Greetings

**Comment by Kra1o5** [comment]
Fixed in  cm-13.0-20160820-UNOFFICIAL-piccolo release.

Greetings
