### ISSUE TITLE
Status message BUG in

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#114]
Size status bar messages is big. Out of screen size!!! 
I dont know how reproduce  it. I see this bug 5 time. Maybe after rotation screen this. Please check it/ 

![screenshot_20160817-120255](https://cloud.githubusercontent.com/assets/5286127/17729336/33c84cb6-647d-11e6-8d06-41be5684db12.png)

**Comment by stucki** [comment]
Never seen this. Does it happen only with Instagram or also with other apps?
Also, I don't think that this is a device specific issue. Please check the upstream issue tracker or report there...

**Comment by Kra1o5** [comment]
Probably because the number of popups.

**Comment by DerSaxxe** [comment]
Never seen this.
@sergiopoverony: Is it gone with the latest builds?

**Comment by sergiopoverony** [comment]
Meybe yes. In now time not see it bug )

**Comment by DerSaxxe** [comment]
Thank you. So I think we can close this issue and reopen if it occurs again.

**Comment by sergiopoverony** [comment]
Yep. Close
