### ISSUE TITLE
Can't update my phone 

### ISSUE THREAD

**Issue by andresako** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#115]
Hi everyone, 
I'm currently using the CM13 20160612 and I'm trying to upgrade the system as always automatically. 
I've downloaded the new patch, click on install, the phone ask me for reboot and say yes. 
The phone never enter on the recovery, making a normal reboot. 
I need to do the patching manually? I need to do some wipes? 
Thanks in advance.

**Comment by stucki** [comment]
I think you need to install the new bootloader first. Get the file "FirmwareMM_v4.1.0_signed.zip    " from https://s.basketbuild.com/devs/eloimuns/bq/piccolo/ and flash it from inside TWRP.

**Comment by andresako** [comment]
Issue fixed. 
Thanks stucki =D
