### ISSUE TITLE
[cm13] after factory reset: can`t enter the cm surface 

### ISSUE THREAD

**Issue by Bondarz** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#119]
hello,

build from the 17.09.2016
after is restet my cm13 m5, you can choose a wifi network. if you skip this **without a wifi network** and **without a sim card**, u can`t enter the cm surface. you can always skip the wifi menue and the sim menue, but can't boot into the cm13 surface.

u have to choose a wifi network. after i selectet a wifi network it was possible to enter the cm13 surface without a sim card.

greetings.

ps: atm i can not paste logs because is delivered my m5 to bq

**Comment by cmorlok** [comment]
This is not a M5 related bug. Please report on CM's JIRA.
