### ISSUE TITLE
Datos móviles

### ISSUE THREAD

**Issue by Migui2356** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#124]
Me detecta la sim, pero no puedo activar mis datos ni usar internet, solo puedo acceder a Internet mediante Wifi

**Comment by stucki** [comment]
Can you please explain your problem in English?

**Comment by ghost** [comment]
hes phone can detect the SIM, but he can´t turn on the cellurar data or use internet, he can only access to internet by Wifi

**Comment by piwats** [comment]
Same here, two sims inserted. card1 is configured to 2G, card2 to LTE.

Status indicator for card1 shows an "x", while that of card2 "E".

Internet goes only when wifi is enabled.

**Comment by ghost** [comment]
I jus translate it my cellurar data works find

**Comment by cmorlok** [comment]
FYI. There is no need to set one card to 2G unless you explicitly want to get a 2G data connection.
