### ISSUE TITLE
Headphones bug

### ISSUE THREAD

**Issue by ghost** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#125]
When I try to plug my headphones inside the phone, it just almost crash.
The phone slow down (extremely laggy), and in any reproductor like spotify or youtube start making noises with the external speaker,

**Comment by cmorlok** [comment]
You have to cherry pick http://review.cyanogenmod.org#/c/164186/

**Comment by cmorlok** [comment]
Duplicate of #126
