### ISSUE TITLE
Can't play music with headphones nor bluetooth

### ISSUE THREAD

**Issue by Migui2356** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#126]
When I plug the headphones or I connect the bluethoot, all music system (how high or low sounds the music and notifications etc) bugs and the mobile starts to go so slow.

**Comment by cmorlok** [comment]
@eloimuns Did you miss to cherry pick http://review.cyanogenmod.org#/c/164186/ ?

**Comment by cmorlok** [comment]
Should be fixed in the 20161018 build. Can you please verify?

**Comment by Migui2356** [comment]
I'm downloading the new build already! But it will take a little long time
because the download is so slow

**Comment by ghost** [comment]
Works find with the 20161018 built
Thanks man you are the best you don't know how much I really appreciated.

**Comment by Migui2356** [comment]
I sent a new Issue, I can't activate my mobile data on this built :( but
the music system works fine!!

2016-10-19 9:25 GMT+02:00 Eloi Carracedo notifications@github.com:
