### ISSUE TITLE
The 20161018 built doesn't let me activate my Mobile Data

### ISSUE THREAD

**Issue by Migui2356** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#127]
The music system (bluethoot and headphones) problem was solved, but I can't activate my Mobile Data, can't activate it with the metod I activated it in the previous build and so, can't navigate or talk on social media.

**Comment by cmorlok** [comment]
Can you please give more details: which steps are you doing to get mobile data? Which is the method to activate you are referring?

**Comment by Migui2356** [comment]
In the previous build I was activating data by going on "options" "mobile
data" and there selecting "LTE(recommended" and not the 2G option, but in
the 20161018 built it doesn't work

**Comment by cmorlok** [comment]
Cannot reproduce.

Can you please tell us exactly step by step what you are doing? Are you starting from a wiped phone? Or have you lost the connection during the update and are not able to re-enable data?

**Comment by Migui2356** [comment]
I started from a wiped phone with the 20161018 build, to try if the music system was fixed, and it was, then I tried to enable data and I couldn't do it in any way, I don't know why, and I posted the issue to see if it was a bug or my problem

**Comment by cmorlok** [comment]
How exactly are you trying to enable mobile data?

**Comment by Migui2356** [comment]
Options>Data Usage>Enable Cellular Data>Cellular Network> LTE (recommended)

**Comment by cmorlok** [comment]
Do you have one or two sims?
Which sim is selected for data usage? (settings - sim cards - preferred sim
for mobile data)
Is the correct APN selected?

**Comment by Migui2356** [comment]
It was the sim card option, it wasn't activated, thanks!
