### ISSUE TITLE
OK google detection

### ISSUE THREAD

**Issue by ghost** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#128]
I found a bug wile activating OK google detection

**Comment by cmorlok** [comment]
What exactly is the bug you found?

**Comment by ghost** [comment]
Google app crash

**Comment by ghost** [comment]
I think that I found the solution.
That happened to me because I activate the google assistant  editing the built.prop
If any one wants to doit you just have to change/edit the values "ro.product.model=Pixel XL" and "ro.opa.eligible_device=true"

**Comment by cmorlok** [comment]
And what exactly is the bug?

**Comment by ghost** [comment]
When you try to activate the ok google detection, It sais "google app keeps stopping" and google app close.
I try to clear cache data... But nothing new always the same message.
But is not a very important think.

**Comment by ghost** [comment]
Fixed its was an error wile flashing the Google app
