### ISSUE TITLE
Video recording doesn't work

### ISSUE THREAD

**Issue by ghost** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#129]
When you try to record some thing and you finish, the camera don't save the videos properly.
Wile trying to reproduce them, it just can't

**Comment by cmorlok** [comment]
Video recording is broken on almost all devices at the moment. This is the main reason why there are no nightlies yet.

Google changed the security concept for the camera which means that the drivers have to be updated. There are a lot of people working on a solution to get it working with the old drivers.

**Comment by ghost** [comment]
Thanks for the information man ,I hope it will be resolved soon

**Comment by cmorlok** [comment]
Video recording is broken on almost all devices at the moment. This is the
main reason why there are no nightlies yet.

Google changed the security concept for the camera which means that the
drivers have to be updated. There are a lot of people working on a solution
to get it working with the old drivers.
