### ISSUE TITLE
File manager starts with error and crashes

### ISSUE THREAD

**Issue by RufioHugo** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#134]
Hi!

My Version: cm-13.0-20161101-NIGHTLY-piccolo
The File manager starts with error message analogous "An Error happened. Procedure could not be executed" and crashes when trying to change location (directory or from phon to SD).
Reports were sent.

Greetings Rufio

**Comment by cmorlok** [comment]
Can you please provide a logcat which includes the crash? If available, please send the tombstone as well.

**Comment by RufioHugo** [comment]
Hello!

As I don't now how much you need ... attached catlog should start with choosing FileManager and end after sending crash report (hopeso).

Greetings Rufio

[File_Man.txt](https://github.com/bq-dev/android_device_bq_piccolo/files/569655/File_Man.txt)

PS:
Right now I can't copy tombstone ... I'll try tomorrow again with an other tool.

**Comment by RufioHugo** [comment]
Updated to cm-13.0-20161106-NIGHTLY-piccolo ... problem solved.
Thank you!

Greetz Rufio
