### ISSUE TITLE
[CM14] mixed languages

### ISSUE THREAD

**Issue by RufioHugo** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#142]
Hi!

My fault, didn't been awake and installed 14-OTA because I misread 13-Update %-)

- Problem = Nearly all menus in phone-options are mixed in translation; choosen language and lots of english.

Greetings Rufio

**Comment by cmorlok** [comment]
Please don't report upstream bugs here.

**Comment by RufioHugo** [comment]
Haven't found/seen it as an upstream bug (and never had such problems before after an "OTA-upgrade") ... sorry!

Rufio

**Comment by cmorlok** [comment]
Just for clarification: upstream = not device specific = appears on other devices as well

We can only provide support for device specific issues, e.g. when hardware is broken. Sorry.
