### ISSUE TITLE
[cm14] system sounds - missing, duped, renamed

### ISSUE THREAD

**Issue by RufioHugo** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#143]
Hi!

My fault, didn't been awake and installed 14-OTA because I misread 13-Update %-)

- Problem = some system sounds are missing, some have a new name and some are dupes.

Didn't find out if this is correct with this version and the number of sounds was reduced and renamed - thanks on information.

Greetings Rufio

**Comment by cmorlok** [comment]
Please don't report upstream bugs here.

I don't know if those sounds are removed/renamed by Google or if the ones you are missing have been added by CM in the past.

**Comment by RufioHugo** [comment]
Haven't found/seen it as an upstream bug ... sorry!

Also sounds were touched if you'ld like to have a look at changelog https://www.cmxlog.com/14.1/piccolo/ - so I thought there could have been made an error.

Rufio
