### ISSUE TITLE
Google Apps not working after update from CM13 to CM14

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#144]
In CM13 version i see and OTA update CM14, after update crash all GoogleServies, dont work GooglePlay Market and etc, dont work AdFree (root acces) not rewrite host, YandexMoney crash after run
For WHAT you sent UPDATE CM14 to CM13 FW??? 
VERY BAD ;(

**Comment by cmorlok** [comment]
For what do you update when you don't want to update? 

Upgrading Android versions always requires to update GApps as well. They are not included in CM for legal reasons. Please downloaded the latest GApps and install them on your phone.

**Comment by sergiopoverony** [comment]
@cmorlok i check it on weekends

**Comment by sergiopoverony** [comment]
@cmorlok i now check. Need update GAPPS 7.1 for work. More time show android.media error. test next
