### ISSUE TITLE
CM13 Stable maybe? 

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#145]
I can hope, wait STABLE version CM13 or you change course to CM14?

**Comment by cmorlok** [comment]
Just use the last nightly (20161122). Calling it stable would just change the name, but not the content. 

If there are too many users staying on 13, we have to decide if we provide monthly builds with security updates only. But don't expect much bug fixing in 13, we don't have the resources to work on multiple (outdated) versions.

**Comment by RufioHugo** [comment]
Well; ... a _BIG_ thanks on all of your efforts anyway from me!

Rufio

**Comment by sergiopoverony** [comment]
@cmorlok KO. I understand. We wait new cm14 for stable ))) Thank you

**Comment by cmorlok** [comment]
We are working on a stable CM13. No eta.

**Comment by sergiopoverony** [comment]
@cmorlok Please upload again to https://download.cyanogenmod.org/?device=piccolo this build cm-13.0-20161122 i see only not last build from cm13  - 2016-08-30 (experremental) need cm-13.0-20161122 this build. Please upload him again to https://download.cyanogenmod.org/

**Comment by stucki** [comment]
FYI A stable release is planned and is just around the corner...

**Comment by sergiopoverony** [comment]
@stucki this is god news )

**Comment by stucki** [comment]
The stable release is here! https://download.cyanogenmod.org/?device=piccolo&type=snapshot
