### ISSUE TITLE
CMUpdater fails to start update

### ISSUE THREAD

**Issue by cmorlok** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#147]
CMUpdater can download new 14.1 nightlies, but the installation fails with the error "Can't boot to recovery". 

This issue will be fixed in the next days with https://review.cyanogenmod.org/#/c/173284/

We have to wait for a new release of TWRP first, otherwise the phone will end up in a boot loop once the updater started his work.

**Comment by RufioHugo** [comment]
Do you mean the new version from today (cm-14.1-20161201-NIGHTLY-piccolo)?

Because I had absolutely no problem with OTA of cm-14.1-20161130-NIGHTLY-piccolo!

Greetings Rufio

**Comment by cmorlok** [comment]
Fixed in 20161207, install TWRP 3.0.2-2 to prevent boot loop.
