### ISSUE TITLE
No SIM cards found

### ISSUE THREAD

**Issue by StephenKing** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#150]
Thanks for the upgrade to CM-14.1!

For the third time after rebooting my phone (out of like 20), the system did not find any SIM cards. At least that's what the icon on top denoted.

Attached is an [`adb logcat` output](https://github.com/bq-dev/DEPRECATED_android_device_bq_piccolo/files/636338/cm14-no-sim.txt). I hope this helps to further debug the issue.

Note: I also have trouble pretty often to get a mobile data connection. Not sure, if this is related. Once this occurs and I have the laptop at hand, I would file a new issue with that as well.

**Comment by cmorlok** [comment]
Is this still an issue with the latest nightly?

**Comment by StephenKing** [comment]
@cmorlok didn't see this recently. Let's close this, I will re-open, as it happens again.
