### ISSUE TITLE
Doble tap don't work

### ISSUE THREAD

**Issue by Alfon7** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#152]
The double-tap to wake the device does not work in 14.1

**Comment by sergiopoverony** [comment]
@Alfon7 reboot device. I now update, in 1-st time dont work, after reboot work fine

**Comment by Alfon7** [comment]
I tried restarting but it still does not work

**Comment by sergiopoverony** [comment]
@Alfon7 may you not switch on this function in settings?

**Comment by cmorlok** [comment]
Works fine for me.

**Comment by Alfon7** [comment]
Where is It?

**Comment by Alfon7** [comment]
For close it works, but don't for wake

**Comment by cmorlok** [comment]
Settings > Display > Tap to wake

**Comment by Alfon7** [comment]
Yes. It is switch

**Comment by RufioHugo** [comment]
Both double-tap worked for me all CM12/13/14 'till today ... only the sensitivity and the speed it needs altered once or twice.

Greetings Rufio

**Comment by cmorlok** [comment]
Please test with stock and re-open this issue if it's a CM only issue. Otherwise call the support, please.
