### ISSUE TITLE
CM14 RO anytime

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#153]
I use adblock app for hide promotions. in cm14 after acces to root not save files in system. Please check it. I cant edit any files in system. maybe selinux or other.

**Comment by cmorlok** [comment]
Closed due to missing information

* Which app is affected
* What exactly is broken
* How to reproduce
* Logfiles missing

Please update the issue and reopen, if necessary.
