### ISSUE TITLE
[CM14.1] Integrated file manager menu won't open on SD-Card

### ISSUE THREAD

**Issue by RufioHugo** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#157]
Not sure if it's a problem of CM14.1-piccolo or upstream;
- open integrated file manager
- change to SD-Card
- select files
- try to open menu
= "An error occured. ..."

If you need a log - make a short note please, but I can provide it at the earliest on Thursday.

Greetings Rufio

**Comment by cmorlok** [comment]
Works fine on 20161214. Please re-open if you still have this issue.
