### ISSUE TITLE
LTE/3G in SIM 2 not working in cm 14.1

### ISSUE THREAD

**Issue by alexgares** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#158]
You can only connect to 2g, I have the last nightly and I update everyday, I use 2 SIMs and it is frustating not being able to use the 3g in the 2nd SIM without swapping them. 

It worked perfectly in CM13

I have tried everything, (restarting, formating, setting SIM 1 to 2g, and SIM 2 to lte...), I can only connect to LTE when I put my SIM in the first slot.

**Comment by stucki** [comment]
I assume this is a duplicate of #140
