### ISSUE TITLE
[CM 14.1]The position sensor errors.

### ISSUE THREAD

**Issue by Alfon7** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#163]
The position sensor when the phone is upright, gives errors.

**Comment by cmorlok** [comment]
Could you please explain

* what the error is (expected vs real behavior)
* how to reproduce

**Comment by Alfon7** [comment]
When I put the phone upright. He thinks he is inclined. I see this with an app that has inclinometer.

**Comment by cmorlok** [comment]
I tested with
https://play.google.com/store/apps/details?id=com.inossoftware.InclinometerFree

Works perfectly.

**Comment by Alfon7** [comment]
I have errors whith two apps: "multi measures" and "nivel brújula".

**Comment by Alfon7** [comment]
Multi Measures 2:
https://play.google.com/store/apps/details?id=com.skypaw.multi_measures

With "plumb Bob"

Nivel Brújula:
https://play.google.com/store/apps/details?id=com.jee.level

**Comment by cmorlok** [comment]
Both apps are working fine on my device. Please test if any of your sensors
is broken using a tool which shows the raw sensor data, e.g.
https://play.google.com/store/apps/details?id=com.wered.sensorsmultitool

**Comment by Alfon7** [comment]
Using CPU-Z, all the sensors are moving, but I don't know if the values are corrects.

**Comment by Alfon7** [comment]
How can I readjust it?

**Comment by Alfon7** [comment]
I have proved one other app, and It give me error too:
Consultar Medir y Alinear - 3D Plomada
https://play.google.com/store/apps/details?id=com.assysto.android.plumb_bob

I think is only in me phone...

**Comment by Alfon7** [comment]
It is the gravity sensor.

**Comment by cmorlok** [comment]
Please test with stock and contact the service if your sensor is broken. Otherwise re-open this issue.
