### ISSUE TITLE
Data connection lost

### ISSUE THREAD

**Issue by Javinator9889** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#167]
When you turn on the plane mode, then you have to reboot the phone because data connection didn't work

**Comment by stucki** [comment]
This is an upstream issue. See the link below for a workaround. If you find any more details on the issue, please report directly to this ticket...
https://jira.lineageos.org/browse/BUGBASH-72

**Comment by cmorlok** [comment]
Duplicate of #136
