### ISSUE TITLE
Bootloop after installing "Nova Launcher" and "Flipboard"

### ISSUE THREAD

**Issue by viggen66** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#177]
Dear Developers.,

On latest edition 25 August, also tried the one from July, if you install "Nova Launcher" the phone gets to bootloop, also with the app "Flipboard" it also hangs, thought of problems of the app itself, but on stock rom it works perfectly, it's a bug from Lineage, as soon the apps get installed the phone is useless.

Could you please check this annoying bug.

**Comment by stucki** [comment]
Can anyone verify & confirm this please?

**Comment by stucki** [comment]
@viggen66 Did you try to reproduce this with a different device? Would be great to know if it happens with other LOS devices too...

**Comment by viggen66** [comment]
Hi sticking

I have tried on a Nexus 7 2013 but it's cyagenmod not lineage and it doesn't go to boot loop only on this device with lineage 13

**Comment by stucki** [comment]
Well, that's obviously not what I asked for...
