### ISSUE TITLE
No mp3 possible for clock alarm

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#26]
_From @SIRSteiner on December 22, 2015 13:53_

In versions prior 20.12. there was no problem choosing mp3 as alarm. Now only ogg is possible.
Many thanks

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#26_

**Comment by stucki** [comment]
_From @Kra1o5 on December 23, 2015 18:11_

Hi @SIRSteiner,

Yeah, https://github.com/CyanogenMod/android_packages_apps_DeskClock/commit/60d907dd2e13350b20d9883b2a55e68f5566ce73

CM add support for OGG files & probably breaks the other formats.

**Comment by stucki** [comment]
_From @SIRSteiner on December 27, 2015 11:24_

Hello! I think this problem needs small changes because if I rename a MP3 to OGG (no convert) I can use it as alarm and it is playing

**Comment by stucki** [comment]
_From @Kra1o5 on December 27, 2015 11:43_

Hi @ SIRSteiner, 

I will check it for next release (not today release).

Greetings

**Comment by stucki** [comment]
Does this issue still exist in cm-13.0?

**Comment by andy-de** [comment]
Seems, it still exist ins Source in CM12.1:https://github.com/CyanogenMod/android_packages_apps_DeskClock/blob/cm-12.1/src/com/android/deskclock/AlarmClockFragment.java
But in CM13.0 it seems, there is no such filter: https://github.com/CyanogenMod/android_packages_apps_DeskClock/blob/cm-13.0/src/com/android/deskclock/AlarmClockFragment.java

**Comment by stucki** [comment]
In any case it would be an upstream issue, so it should be reported at https://jira.cyanogenmod.org/ instead. Closing here.
