### ISSUE TITLE
Double tap activation not working when charging

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#42]
_From @piwats on January 28, 2016 12:37_

When the phone is charging and the charging cable is connected, double tap to activate is **not** working/responding.

When not charging and the cable is disconnected, double tap is working as it should.

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#42_

**Comment by stucki** [comment]
_From @piwats on January 28, 2016 12:53_

Does only happen when on external charger.

When connected to a laptop, it seems to work though.

**Comment by stucki** [comment]
_From @piwats on January 29, 2016 10:32_

Seems to not work only if charging, e.g. <95%.

**Comment by stucki** [comment]
_From @Kra1o5 on January 30, 2016 23:21_

We can take a look into it.

@eloimuns can test it?

**Comment by DerSaxxe** [comment]
No problems here with the latest nightly.

**Comment by stucki** [comment]
Closing the issue. Please reopen if the problem still occurs.
