### ISSUE TITLE
Problems with Bluetooth

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#54]
_From @fermaxando on February 19, 2016 23:3_

When i will going to share my conexion from bluetooth by PAN Network (Wifi's zone section), the computer doesn't connect y was try with 3 computers with differents bluetooth.

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#54_

**Comment by stucki** [comment]
_From @Kra1o5 on February 28, 2016 12:45_

Hi,

Please specific version of CM.

Greetings

**Comment by cmorlok** [comment]
No response. Please reopen and provide additional information if the issue still exists.
