### ISSUE TITLE
SIM not available on first boot after update

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#55]
_From @cmorlok on February 22, 2016 20:59_

Directly after an update (rebooting directly from TWRP), SIMs are sometimes not available. Everything is fine after rebooting.

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#55_

**Comment by stucki** [comment]
_From @Kra1o5 on February 22, 2016 21:1_

Really weird, maybe upstream issue?

For now I cant reproduce it, @eloimuns you did?

**Comment by stucki** [comment]
_From @cmorlok on February 22, 2016 21:9_

It's not really reproduceable, I get it on about 1 of 10 updates. On the german forum one guy reported the issue as well after an OTA update. It might be a timing issue.

**Comment by stucki** [comment]
@cmorlok Does this problem still exist for you? I have never noticed it myself...

**Comment by cmorlok** [comment]
Haven't noticed the bug since February, it seems to be gone.
