### ISSUE TITLE
Battery status and LED "freeze" after loading

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#59]
_From @bonanzabike on March 6, 2016 21:8_

After loading the battery overnight and unplugging the cable next morning the status LED still remains shining green and the battery level remains at 100%, even if I use the phone for hours.
The monitoring of the battery level in the battery settings section stopped in the middle of the night, shortly after it reached the 100%.

Rebooting solved the problem, but another user told me he had this bug sporadically, too, until one day it disappeared.

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#59_

**Comment by stucki** [comment]
_From @bonanzabike on March 6, 2016 21:11_

oh, I forgot to tell that I was using cm-13.0-20160228 build from https://s.basketbuild.com/devs/eloimuns/bq/piccolo/

**Comment by stucki** [comment]
_From @Kra1o5 on March 20, 2016 11:23_

Really weird @bonanzabike I will try to reproduce it.

**Comment by DerSaxxe** [comment]
I think this is an old issue. I never seen this since months. I think we can close it?

**Comment by DerSaxxe** [comment]
Should be closed...

**Comment by stucki** [comment]
Closing the issue. Please reopen if the problem still occurs.
