### ISSUE TITLE
cm13 apollo music player not working properly on car bluetooth

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#66]
_From @Greatdroid on March 20, 2016 22:13_

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#66_

**Comment by stucki** [comment]
_From @Kra1o5 on March 20, 2016 22:15_

You refer to Eleven right?

**Comment by stucki** [comment]
_From @Greatdroid on March 20, 2016 22:20_

Sorry don't get it. What do you mean by eleven?

**Comment by stucki** [comment]
_From @Kra1o5 on March 20, 2016 22:21_

CM not using Apollo from CM12.1+, now use Eleven.

**Comment by stucki** [comment]
_From @Greatdroid on March 20, 2016 22:25_

Sorry didn't know they changed the name, but yes, I mean that one. :-)

**Comment by cmorlok** [comment]
Can this be closed now?

**Comment by Greatdroid** [comment]
It still doesn't work. No need to close yet

**Comment by Greatdroid** [comment]
I think it works now, the only issue I found that it doesn't auto play the music when it connects via bluetooth. Once you press play on the phone then I can change tracks from the car
