### ISSUE TITLE
Audio on call by bluetooth in car radio

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#67]
_From @papachiclas on March 20, 2016 22:36_

I have had problems with the audio on the car radio while on call by bluethooth. Most of the time the sound is very bad, It is impossible to understand what people say

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#67_

**Comment by DerSaxxe** [comment]
No problems here with the latest nightly in daily use.

**Comment by stucki** [comment]
I can confirm that, using multiple bluetooth headsets for many months now without issues: Belkin AirCast, Sony SBH-70, Bose Soundlink Mini

Closing the issue. Please reopen if the problem still occurs.
