### ISSUE TITLE
CM13 file manager doesn't show OTG-Devices

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#70]
_From @SIRSteiner on March 28, 2016 17:52_

Maybe a CM issue? 

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#70_

**Comment by stucki** [comment]
_From @Kra1o5 on March 29, 2016 18:37_

Pretty sure yes.

@eloimuns can test it you too?

**Comment by stucki** [comment]
_From @eloimuns on March 29, 2016 19:4_

Seems to be a CM problem. I just tested with Xiaomi Redmi 1S and Xiaomi mi4 and the same result.

**Comment by cha25228** [comment]
Talk back

**Comment by DerSaxxe** [comment]
With the tomorrows build the issue still exist.

**Comment by Kra1o5** [comment]
I think is a upstream issue not device specific, @stucki @cmorlok @eloimuns what do you think?

**Comment by stucki** [comment]
I just checked on Moto G (peregrine) and the issue exists there as well.
Found no upstream issue, however it's reported for CyanogenOS on the OnePlus One: https://jira.cyanogenmod.org/browse/BACON-4710

So I think this issue can be closed because it's an upstream bug.
