### ISSUE TITLE
Restart into recovery doesn't work

### ISSUE THREAD

**Issue by DerSaxxe** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#77]
If you want to restart into recovery with restart menu the device reboots into CM.

**Comment by danny9484** [comment]
the same happens for CM updates. it just reboots into CM
you have to install updates manually via twrp from /sdcard/cmupdater

**Comment by DerSaxxe** [comment]
With the latest build and the new bootloader this problem is gone here.

**Comment by danny9484** [comment]
nope, choosing recovery in the restart menu doesn't work here with latest CM. But the update worked.

**Comment by stucki** [comment]
I can confirm that the problem is gone with the latest build.
