### ISSUE TITLE
Camera problem

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#85]
_From @CarreyCC on May 24, 2016 7:32_

When opening the camera from the lock screen, to put it in landscape mode, the image is displaced and only the top part is visible.
Hopefully soon be resolved because continually use this option.
Thank you and congratulations for your work

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#84_

**Comment by DerSaxxe** [comment]
Here the camera app is crashing while starting from lock screen in landscape mode. 
[tmp_16732-2016-06-01-06-45-30-1574994631.txt](https://github.com/bq-dev/android_device_bq_piccolo/files/292667/tmp_16732-2016-06-01-06-45-30-1574994631.txt)

**Comment by CarreyCC** [comment]
When this will resolve, please?
I have installed 31 may version and still the issue.
Thanks a lot

**Comment by eloimuns** [comment]
Can you try to change phone language and test it again? 

Thanks!

**Comment by CarreyCC** [comment]
Hello.

The problem is the same at English and Spanish language.

Thanks a lot.

**Comment by DerSaxxe** [comment]
No problems here with the latest nightly.

**Comment by stucki** [comment]
Thanks for the feedback! @CarreyCC please reopen if the problem comes back.
