### ISSUE TITLE
CM13 wrong autoupdate notification

### ISSUE THREAD

**Issue by stucki** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#86]
_From @danny9484 on May 25, 2016 12:0_

I have set the check for update feature in the settings app to every day and it gives me a notification that a new update is available even though there isn't. If I go to the settings and check for updates manually it tells that none are available but on the notification I can press download and it install the same version again. 

_Copied from original issue: piccolo-dev/android_device_bq_piccolo#85_

**Comment by stucki** [comment]
I can confirm this. Happens to me every day :)

**Comment by sergiopoverony** [comment]
Yep. Happens every day )))))

**Comment by stucki** [comment]
@Kra1o5 This is pretty annoying and still happens every day. Do you have an idea why it happens?

**Comment by Kra1o5** [comment]
@stucki Probably server side, but I cant do much, maybe @eloimuns ?

Regards

**Comment by stucki** [comment]
Seems to be fixed now.
