### ISSUE TITLE
CM13 Eleven Music player doesn't change music tracks through car bluetooth device

### ISSUE THREAD

**Issue by Greatdroid** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#88]
Other music players like google play music does work.

**Comment by Greatdroid** [comment]
Other music players like Google play music does works.

**Comment by stucki** [comment]
This sounds like an upstream issue. I suggest that you check at https://jira.cyanogenmod.org/ if the problem is already known. Please close here if the issue is reported there.

**Comment by Greatdroid** [comment]
Ok. In the last beta from yesterday, still doesn't work.

**Comment by Kra1o5** [comment]
Duplicate here: https://github.com/bq-dev/android_device_bq_piccolo/issues/66
