### ISSUE TITLE
GAPPS trouble

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#91]
# **hello again.**

Step Install CM13 - run device - ALL OK
reset data/chache and etc
reboot to TRWP - install GAPPS (any pack from opengaaps)
 run device - error gapps wizard and etc.

Step Install CM13 - run device - ALL OK
 reboot to TRWP - install GAPPS (any pack from opengaaps)
reset data/chache and etc
 run device - error gapps wizard and etc.

Step Install CM13 - run device - ALL OK
reset data/chache and etc
reboot to TRWP - install GAPPS (any pack from opengaaps)
 reset data/chache and etc
run device - error gapps wizard and etc.

 format all ;) 

Please give me link to good work Gapps for CM13 or give fix
Thank you

**Comment by eloimuns** [comment]
Try with this:

https://www.androidfilehost.com/?fid=24533103863142104

**Comment by sergiopoverony** [comment]
Thank you

**Comment by stucki** [comment]
I usually have no issues with OpenGapps. If you have a problem just try with the build from the day before or so. For the Aquaris M5 I recommend to use Nano / x86 / 6.0.

**Comment by sergiopoverony** [comment]
i install from here https://www.androidfilehost.com/?fid=24533103863142104
is that the system ceases to be writable. It is necessary to sew through fastboot
You can then put the GAPPS and SU(beta)

**Comment by stucki** [comment]
Sorry, but I don't understand what you mean. Nevermind, the problem seems solved.
