### ISSUE TITLE
process freezes

### ISSUE THREAD

**Issue by danny9484** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#92]
with the CM version 20160530 I had some freezes with chrome. But today it froze my statusbar and time. My alarm clock didn't work too.
some screenshots:
https://www.dropbox.com/s/xdxt5kewh5m1jo0/Screenshot_20160601-070648.png?dl=0
https://www.dropbox.com/s/p84qk82dlmqz78w/Screenshot_20160601-070659.png?dl=0

after reboot

https://www.dropbox.com/s/xv226oeokrzeqjy/Screenshot_20160601-070937.png?dl=0

**Comment by stucki** [comment]
Had several issues with 2016-05-30 too. Please try again with 2016-05-31. It should be fine now.

**Comment by danny9484** [comment]
yeah no issues so far with the new CM version.
