### ISSUE TITLE
CM13 - SD card and Write problem

### ISSUE THREAD

**Issue by sergiopoverony** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#93]
For edit text file on my sdcard, me need root.
I switch On root in settings.
Now 1-st save - work ok. after edit again - save document not work need reboot device
(i use Default File Manager, EsExplorer, RootBrowser and ETC.)

**Comment by sergiopoverony** [comment]
Hello Again. 
**_PLEASE TEST IT**_
`system/etc/permissions/platform.xml
 add <group gid="media_rw" /> in the following location like so:
<permission name="android.permission.WRITE_EXTERNAL_STORAGE" >
<group gid="sdcard_r" />
<group gid="sdcard_rw" />
<group gid="media_rw" />
</permission>`

**Comment by Kra1o5** [comment]
Hi,

We cant do that because is a nasty hack.

Normally, file explorer have the option to do that ( Fxplorer for example).

Greetings

**Comment by sergiopoverony** [comment]
hi, no, i open txt file on sdcard witch default FSbrowser, edit him.  After 1 min. i edit him again, i want save him. and i see NoSaved - no Root Previl.... 
Please check it

**Comment by Kra1o5** [comment]
Yes, default filemanager is basic & a bit buggy actually.

**Comment by sergiopoverony** [comment]
Any FS browser  not save changes, what you write Fxplorer

**Comment by Kra1o5** [comment]
You try on external sdcard or internal?

**Comment by sergiopoverony** [comment]
External sdcard after 1st write - only read,. after reboot device - again only 1 write

**Comment by Kra1o5** [comment]
Weird, not problem in my device.

You have sdcard formated as internal or portable storage?

**Comment by sergiopoverony** [comment]
make as portable storage

**Comment by Kra1o5** [comment]
I test it, no problems detected @eloimuns @cmorlok @stucki can you reproduce it?

Greetings

**Comment by sergiopoverony** [comment]
I check again. It it bug after give root access any FileManager (FM) 
After delete all FM and reset setting default FM - work aging is fine.
i dont know how and why. Edit only use FM Editor. Other Editors not work

**Comment by cmorlok** [comment]
I cannot reproduce this issue. Tested with ASUS File Manager, Total
Commander and Root Explorer. Editing and saving files multiple times work
fine on SD card and on internal storage.

**Comment by sergiopoverony** [comment]
Fixed/ Close
