### ISSUE TITLE
Movistar SIM whitouth Data no find 3G/4G networks [RC, 31-05-2016, Firmware 6.0]

### ISSUE THREAD

**Issue by Mutilo** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#95]
I have build RC, 31-05-2016 (firmware 6.0, @eloimuns) with two SIM (Spain), one of Mundo-R with data, and other of Movistar without data, only voice. In "SIM preferred to > Mobile Data" I put the R SIM.

As in some places I have not Movistar 2G coverage, in "Preferred network type" I have to put this SIM as 3G/LTE, because it's more important that this SIM have coverage. The R SIM I put in 2G, it receives signal E, but in these cases I don't care.

In my case, when I set:

```
"SIM preferred to > Mobile Data" > R SIM,
"Settings" R SIM > "Preferred network type" > 2G,
"Settings" Movistar SIM > "Preferred network type" > 3G / LTE
```

in "Settings" Movistar SIM > "Network operators" it only finds 2G networks of any operator (Vodafone/Movistar/Orange/Yoigo), no 3G or 4G.

I do a test:
if in "SIM preferred to > Mobile Data" I put the Movistar SIM (although it has no data) now it displayed to select all 2G, 3G and 4G networks of all operators.

With the build Beta 18-05-2016 and base 5.1.1, that has not happened

**Comment by stucki** [comment]
It could be that there were issues with the 2016-05-31 release (I think I've had the same issues) but it works fine right now with a current build. Please check again as soon as the next release is out. (see also #96).

**Comment by Mutilo** [comment]
Hi. My problem is similar to # 96, but to me It does seem to be possible to set SIM1 to 2G. Indeed, I can also set the mode to LTE for both SIM cards.

In my case, if I try to set SIM1 to 2G, "SIM preferred to > Mobile Data" set SIM1, and set SIM2 to 3G, SIM2 will only discover 2G networks

If I try to set "SIM preferred to > Mobile Data" SIM2, SIM2 discovers 2G, 3G and 4G networks

**Comment by stucki** [comment]
I think I know the reason of your issue: It doesn't matter if you set SIM 1 to 2G, 3G or 4G. When it's selected for mobile data, then it means it's the active SIM. While this happens, SIM 2 is always limited to 2G.

Therefore, if you want to select a different network for SIM 2, you need to select if for mobile data to make it active first.

Can you confirm that this works? If so, I don't think it's a bug, so it can be closed.

**Comment by Mutilo** [comment]
All this is correct. But in previous builds I don't have that issue:

Before, I could set SIM1 to 2G and select for mobile data, and set SIM2 to 3G or 4G. Although SIM1 was select for mobile data, SIM2 isn't limited to 2G, it was connected to 3G or 4G networks.

**Comment by stucki** [comment]
If this was the case then it was wrong before and is fixed now. When SIM 1 is active, you cannot connect to anything except 2G networks on SIM 2. It's just not possible.

**Comment by Mutilo** [comment]
Ok ok...

So it was that was wrong before, but in my case it was better before :DDDD

**Comment by stucki** [comment]
In fact, I think it's a bug that you see all these 2G / 3G / 4G networks. You should only see one of them while the network type is chosen automatically by availability.

To verify this, make the following test:
- Activate SIM 2 for mobile data
- Open the carrier list for SIM 1. You should only see 2G networks. Choose your carrier.
- Set the preferred network type for SIM 1 to 4G
- Now change mobile data from SIM 2 to SIM 1 and open the carrier list again. If it's available at your place, the phone will connect to 4G even if you selected the 2G network before.

Not sure if that is a bug or a feature, however it's not device specific, so I'm closing here.

If you like, you can report the issue again to the CyanogenMod team at https://jira.cyanogenmod.org/.
