### ISSUE TITLE
SIM1 cannot select 2G; SIM2 cannot use 3G

### ISSUE THREAD

**Issue by StarGW-net** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#96]
I have tested cm-13.0-20160531-UNOFFICIAL-piccolo.zip and most things seem to be working well. Excellent work.

But I am having sokme issues with dual SIM:

1) There is no way to individually disable SIMs. (i.e. disable SIM1 completely)
2) It does not seem to be possible to set SIM1 to 2G. (It discovers 3G and 2G networks)
3) Even if you try to set SIM2 to 3G it will only discover 2G networks

In the standard BQ Android ROM you can disable SIMs and select which one is 2G. In this ROM the second SIM is always 2G and now requires the SIM cards to be manually swapped in the slots.

Screenshots of the issues here: http://www.stargw.eu/4ZYhEGFkocRRhJcz0lRWk-HBoLUw

As I use dual SIMs a lot, this is a killer issue for me. Any chance of getting this fixed, because aside from that it works like a dream.

Thanks,

-S

**Comment by stucki** [comment]
~~I can confirm this. Happens with the 20160531 ROM, didn't happen before that (using the old piccolo-dev repositories).~~
Just tried again today with a current build (compiled locally). In fact it seems like switching from SIM 1 to SIM 2 and back works as good as before the refactoring.
Besides this, I notice that I can set the mode to LTE for both SIM cards and the system automatically chooses LTE for the SIM which is currently active.

**Comment by stucki** [comment]
So, looking at this issue again, I think that 1) is an upstream issue. It just looks like this feature is currently not available in CyanogenMod 13.0. See https://jira.cyanogenmod.org/browse/CYAN-7560

Points 2) and 3) do not occur for me with the latest build from yesterday (2016-06-12). I'm using SIM 1 as well as SIM 2 with LTE without issues. Can you please try again with the latest build?

**Comment by cmorlok** [comment]
_1) There is no way to individually disable SIMs. (i.e. disable SIM1 completely)_
This needs closed source QTI telephony extension. I have to check if there is one available which is compatible for our device. The last time I searched I couldn't find any.

_2) It does not seem to be possible to set SIM1 to 2G. (It discovers 3G and 2G networks)_
Works with the latest build.

_3) Even if you try to set SIM2 to 3G it will only discover 2G networks_
Only the SIM which is selected for data is able to discover 3G or 4G networks.
