### ISSUE TITLE
responsiveness

### ISSUE THREAD

**Issue by starvoid** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#97]
Hi all, I was using 20160508 version more or less well. Since I moved to 20160531 my device is responsiveness. Some apps (as Clash of clans) are not open at first touch, and even when I achieve to open them, they are not usable by the lack of response.

It seems that this is only happening to me, maybe the responsible is some special app that I have installed. If so, I'd like to know.

Please, if somebody else has the same problem, please tell.

I'm considering go again to 20160508 until a new release shows up.

Regards and thanks to developer by the effort.

**Comment by DerSaxxe** [comment]
Can't confirm this issue, no problems here with the latest nightly

**Comment by stucki** [comment]
Closing the issue. Please reopen if the problem still occurs.
