### ISSUE TITLE
CM13 + TWRP 3.0.2-1 -> wrong TWRP password

### ISSUE THREAD

**Issue by Bondarz** [aquaris-dev/DEPRECATED_android_device_bq_piccolo#98]
hello,

started also a thread inside the twrp board, hope this is ok:
link: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/699

**Comment by stucki** [comment]
That makes sense, thank you! Since it's a TWRP issue, I think it's fine to close it on this side. Ok?

**Comment by Kra1o5** [comment]
I think is a combination, we inform of any advance here dont worry.
